/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacherhelper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ViSion
 */
public class StudentGui extends javax.swing.JFrame {

    /**
     * Creates new form StudentGui
     */
    private Student student;
    CareTaker careTaker;

    public StudentGui(User user) throws SQLException {
        student = (Student) user;
        careTaker = new CareTaker();
        careTaker.add(student.saveStateToMemento());
        initComponents();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTable.setDefaultRenderer(String.class, centerRenderer);
        jTable.setDefaultEditor(Object.class, null);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultEditor(Object.class, null);
        jTable2.setDefaultRenderer(String.class, centerRenderer);
        jTable2.setDefaultEditor(Object.class, null);

        ResultSet rs = JdbcSingleton.getInstance().getALLSubjectNames();
        while (rs.next()) {
            subjectsCb.addItem(rs.getString("name"));
        }
        rs = JdbcSingleton.getInstance().getChosenSubjectsNames(student.getId());
        while (rs.next()) {
            subjectCb.addItem(rs.getString("name"));
        }
        loadSubmissions();
        loadView();
        loadProjectsView();
    }

    public void loadView() throws SQLException {
        jTable.setModel(JdbcSingleton.getInstance().getChosenSubjects(student.getId(), jTable.getModel()));
    }

    public void loadProjectsView() throws SQLException {

        if (subjectCb.getSelectedIndex() != -1) {

            JdbcSingleton.getInstance().getSubjectProjects(subjectCb.getSelectedItem().toString(), jTable1.getModel());
        }
    }

    public boolean allSubmitInfoAvailable() {
        return (!(projectIdTf.getText().equals("") || linkTf.getText().equals("")));
    }

    public void loadSubmissions() throws SQLException {
        JdbcSingleton.getInstance().getUserSubmissions(student.getId(), jTable2.getModel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        chooseSubjectPnl = new javax.swing.JPanel();
        chooseSubjectsLbl = new javax.swing.JLabel();
        subjectsPnl = new javax.swing.JPanel();
        subjectsLbl = new javax.swing.JLabel();
        subjectsCb = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        addSubjectBtn = new javax.swing.JButton();
        removeSubjectBtn = new javax.swing.JButton();
        viewProjectsPnl = new javax.swing.JPanel();
        projectInfoPnl = new javax.swing.JPanel();
        subjectLbl = new javax.swing.JLabel();
        subjectCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        submitProjectPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        projectIdLbl = new javax.swing.JLabel();
        projectIdTf = new javax.swing.JTextField();
        linkLbl = new javax.swing.JLabel();
        linkTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        editProfilePnl = new javax.swing.JPanel();
        profilePnl = new javax.swing.JPanel();
        nameEditLbl = new javax.swing.JLabel();
        nameEditTf = new javax.swing.JTextField();
        lastNameEditLbl = new javax.swing.JLabel();
        lastNameEditTf = new javax.swing.JTextField();
        phoneEditLbl = new javax.swing.JLabel();
        phoneEditTf = new javax.swing.JTextField();
        userNameEditLbl = new javax.swing.JLabel();
        userNameEditTf = new javax.swing.JTextField();
        editProfileLbl = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        changePasswordPnl = new javax.swing.JPanel();
        changePasswordLbl = new javax.swing.JLabel();
        passwordInfoPnl = new javax.swing.JPanel();
        oldPassLbl = new javax.swing.JLabel();
        oldPassTf = new javax.swing.JTextField();
        newPassLbl = new javax.swing.JLabel();
        newPassTf = new javax.swing.JTextField();
        confirmPassLbl = new javax.swing.JLabel();
        confirmPassTf = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        logoutPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Gui");

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        chooseSubjectsLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        chooseSubjectsLbl.setText("CHOOSE SUBJECTS");

        subjectsPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subjectsLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        subjectsLbl.setText("Subjects");

        subjectsCb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout subjectsPnlLayout = new javax.swing.GroupLayout(subjectsPnl);
        subjectsPnl.setLayout(subjectsPnlLayout);
        subjectsPnlLayout.setHorizontalGroup(
            subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectsPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(subjectsLbl)
                .addGap(54, 54, 54)
                .addComponent(subjectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        subjectsPnlLayout.setVerticalGroup(
            subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectsPnlLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectsLbl)
                    .addComponent(subjectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SUBJECT", "CREDITS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTable);

        addSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addSubjectBtn.setText("ADD SUBJECT");
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        removeSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        removeSubjectBtn.setText("REMOVE SUBJECT");
        removeSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubjectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseSubjectPnlLayout = new javax.swing.GroupLayout(chooseSubjectPnl);
        chooseSubjectPnl.setLayout(chooseSubjectPnlLayout);
        chooseSubjectPnlLayout.setHorizontalGroup(
            chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(subjectsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(addSubjectBtn)
                        .addGap(53, 53, 53)
                        .addComponent(removeSubjectBtn)))
                .addContainerGap(633, Short.MAX_VALUE))
            .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                    .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(chooseSubjectsLbl))
                        .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                            .addGap(499, 499, 499)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        chooseSubjectPnlLayout.setVerticalGroup(
            chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(subjectsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubjectBtn)
                    .addComponent(removeSubjectBtn))
                .addContainerGap())
            .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(chooseSubjectsLbl)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Choose Subjects", chooseSubjectPnl);

        projectInfoPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subjectLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subjectLbl.setText("Subject");

        subjectCb.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subjectCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subjectCbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout projectInfoPnlLayout = new javax.swing.GroupLayout(projectInfoPnl);
        projectInfoPnl.setLayout(projectInfoPnlLayout);
        projectInfoPnlLayout.setHorizontalGroup(
            projectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectInfoPnlLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(subjectLbl)
                .addGap(87, 87, 87)
                .addComponent(subjectCb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        projectInfoPnlLayout.setVerticalGroup(
            projectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectInfoPnlLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(projectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLbl)
                    .addComponent(subjectCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "DUE DATE", "PROJECT LINK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("VIEW PROJECTS");

        javax.swing.GroupLayout viewProjectsPnlLayout = new javax.swing.GroupLayout(viewProjectsPnl);
        viewProjectsPnl.setLayout(viewProjectsPnlLayout);
        viewProjectsPnlLayout.setHorizontalGroup(
            viewProjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProjectsPnlLayout.createSequentialGroup()
                .addGroup(viewProjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewProjectsPnlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(projectInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewProjectsPnlLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        viewProjectsPnlLayout.setVerticalGroup(
            viewProjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProjectsPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(viewProjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(projectInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Projects", viewProjectsPnl);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        projectIdLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        projectIdLbl.setText("Project Id");

        projectIdTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        linkLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        linkLbl.setText("Link");

        linkTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectIdLbl)
                    .addComponent(linkLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projectIdTf)
                    .addComponent(linkTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectIdLbl)
                    .addComponent(projectIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLbl)
                    .addComponent(linkTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("SUBMIT PROJECT");

        submitBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROJECT ID", "SUBMISSION DATE", "LINK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout submitProjectPnlLayout = new javax.swing.GroupLayout(submitProjectPnl);
        submitProjectPnl.setLayout(submitProjectPnlLayout);
        submitProjectPnlLayout.setHorizontalGroup(
            submitProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitProjectPnlLayout.createSequentialGroup()
                .addGroup(submitProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(submitProjectPnlLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2))
                    .addGroup(submitProjectPnlLayout.createSequentialGroup()
                        .addGroup(submitProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(submitProjectPnlLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(submitProjectPnlLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(submitBtn)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        submitProjectPnlLayout.setVerticalGroup(
            submitProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitProjectPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(submitProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Submit Project", submitProjectPnl);

        profilePnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profilePnl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        nameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameEditLbl.setText("Name");

        nameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        lastNameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lastNameEditLbl.setText("Last Name");

        lastNameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        phoneEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        phoneEditLbl.setText("Phone");

        phoneEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        userNameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        userNameEditLbl.setText("UserName");

        userNameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout profilePnlLayout = new javax.swing.GroupLayout(profilePnl);
        profilePnl.setLayout(profilePnlLayout);
        profilePnlLayout.setHorizontalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameEditLbl)
                    .addComponent(phoneEditLbl))
                .addGap(39, 39, 39)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameEditTf)
                    .addComponent(phoneEditTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(173, 173, 173)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameEditLbl)
                    .addComponent(userNameEditLbl))
                .addGap(45, 45, 45)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameEditTf)
                    .addComponent(userNameEditTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        profilePnlLayout.setVerticalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditLbl)
                    .addComponent(nameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameEditLbl)
                    .addComponent(lastNameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneEditLbl)
                    .addComponent(phoneEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameEditLbl)
                    .addComponent(userNameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        editProfileLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        editProfileLbl.setText("EDIT PROFILE");

        editProfileBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        editProfileBtn.setText("EDIT");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProfilePnlLayout = new javax.swing.GroupLayout(editProfilePnl);
        editProfilePnl.setLayout(editProfilePnlLayout);
        editProfilePnlLayout.setHorizontalGroup(
            editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePnlLayout.createSequentialGroup()
                .addGroup(editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(editProfileLbl))
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        editProfilePnlLayout.setVerticalGroup(
            editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePnlLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(editProfileLbl)
                .addGap(28, 28, 28)
                .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Edit Profile", editProfilePnl);

        changePasswordLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        changePasswordLbl.setText("CHANGE PASSWORD");

        passwordInfoPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordInfoPnl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        oldPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        oldPassLbl.setText("Old Password");

        oldPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        newPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        newPassLbl.setText("New Password");

        newPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        confirmPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        confirmPassLbl.setText("Confirm Password");

        confirmPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout passwordInfoPnlLayout = new javax.swing.GroupLayout(passwordInfoPnl);
        passwordInfoPnl.setLayout(passwordInfoPnlLayout);
        passwordInfoPnlLayout.setHorizontalGroup(
            passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPassLbl)
                            .addComponent(newPassLbl)))
                    .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(confirmPassLbl)))
                .addGap(116, 116, 116)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldPassTf)
                    .addComponent(newPassTf)
                    .addComponent(confirmPassTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        passwordInfoPnlLayout.setVerticalGroup(
            passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLbl)
                    .addComponent(oldPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassLbl)
                    .addComponent(newPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassLbl)
                    .addComponent(confirmPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        confirmBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        confirmBtn.setText("CONFIRM");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        undoBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        undoBtn.setText("UNDO");
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePasswordPnlLayout = new javax.swing.GroupLayout(changePasswordPnl);
        changePasswordPnl.setLayout(changePasswordPnlLayout);
        changePasswordPnlLayout.setHorizontalGroup(
            changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPnlLayout.createSequentialGroup()
                .addGroup(changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(changePasswordLbl))
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(passwordInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        changePasswordPnlLayout.setVerticalGroup(
            changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(changePasswordLbl)
                .addGap(30, 30, 30)
                .addComponent(passwordInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Change Password", changePasswordPnl);

        javax.swing.GroupLayout logoutPnlLayout = new javax.swing.GroupLayout(logoutPnl);
        logoutPnl.setLayout(logoutPnlLayout);
        logoutPnlLayout.setHorizontalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        logoutPnlLayout.setVerticalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Logout", logoutPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
        if (subjectsCb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please Choose A Subject First");
        } else {

            try {
                if (JdbcSingleton.getInstance().searchChosenSubject(subjectsCb.getSelectedItem().toString(), student.getId())) {
                    JOptionPane.showMessageDialog(this, "Subject Already Chosen In You List !!");
                } else {

                    int subjectId = 0;
                    ResultSet rs = JdbcSingleton.getInstance().getSubjectId(subjectsCb.getSelectedItem().toString());
                    while (rs.next()) {
                        subjectId = rs.getInt("subjectId");
                    }
                    student.SubjectChoice(student.getId(), subjectId);

                    JOptionPane.showMessageDialog(this, "Subject succesfuly added to your subject list");
                    DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                    model.setRowCount(0);
                    loadView();
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    private void removeSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubjectBtnActionPerformed
        if (jTable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "You Didnt Make A Selection !!");
        } else {
            int selectedIndex = jTable.getSelectedRow();
            try {
                student.subjectRemove(student.getId(), Integer.parseInt(jTable.getValueAt(selectedIndex, 0).toString()), this);
                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);
                loadView();
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_removeSubjectBtnActionPerformed

    private void subjectCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subjectCbItemStateChanged
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            loadProjectsView();
        } catch (SQLException ex) {
            Logger.getLogger(TeacherGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subjectCbItemStateChanged

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        try {
            student.editProfile(student, nameEditTf.getText(), lastNameEditTf.getText(), phoneEditTf.getText(), userNameEditTf.getText(), this);
            student.setName(nameEditTf.getText());
            student.setLastName(lastNameEditTf.getText());
            student.setPhone(phoneEditTf.getText());
            student.setUsername(userNameEditTf.getText());
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (oldPassTf.getText() == "" || newPassTf.getText() == "" || confirmPassTf.getText() == "") {
            JOptionPane.showMessageDialog(this, "Some Fields Are Missing !!");
        } else {
            try {
                if (!JdbcSingleton.getInstance().verifyOldPassword(student, oldPassTf.getText())) {
                    JOptionPane.showMessageDialog(this, "Wrong Old Password !!");
                } else {

                    if (!newPassTf.getText().equals(confirmPassTf.getText())) {
                        JOptionPane.showMessageDialog(this, "New Pass And Confirmation Are Not The Same !!");
                    } else {
                        student.changePassword(student, newPassTf.getText(), this);
                        student.setPassword(newPassTf.getText());
                        careTaker.add(student.saveStateToMemento());

                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        if (careTaker.getList().size() > 1) {
            try {
                student.changePassword(student, careTaker.get(careTaker.getList().size() - 2).getState(), this);
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }

            student.setPassword(careTaker.get(careTaker.getList().size() - 2).getState());

            careTaker.getList().remove(careTaker.getList().size() - 1);
        } else {
            JOptionPane.showMessageDialog(this, "There Is Nothing To Undo !!");
        }
    }//GEN-LAST:event_undoBtnActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

        if (jTabbedPane1.getSelectedIndex() == 3) {
            try {

                ResultSet rs = JdbcSingleton.getInstance().loadProfile(student);
                while (rs.next()) {
                    nameEditTf.setText(rs.getString("name"));
                    lastNameEditTf.setText(rs.getString("lastname"));
                    phoneEditTf.setText(rs.getString("phone"));
                    userNameEditTf.setText(rs.getString("username"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jTabbedPane1.getSelectedIndex() == 5) {
            student.logout(this);
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (allSubmitInfoAvailable()) {
            try {
                if (JdbcSingleton.getInstance().searchProjectId(Integer.parseInt(projectIdTf.getText()))) {

                    if (JdbcSingleton.getInstance().alreadySubmitted(Integer.parseInt(projectIdTf.getText()), student.getId())) {
                        JOptionPane.showMessageDialog(this, "Project Already Submitted !!");
                    } else {
                        student.submitProject(student.getId(), Integer.parseInt(projectIdTf.getText()), linkTf.getText());
                        JOptionPane.showMessageDialog(this, "Project Submitted Successfuly !!");
                        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                        model.setRowCount(0);
                        loadSubmissions();
                        projectIdTf.setText("");
                        linkTf.setText("");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "This Project Does Not Exist !!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(StudentGui.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Some Info Are Missing !!");
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JLabel changePasswordLbl;
    private javax.swing.JPanel changePasswordPnl;
    private javax.swing.JPanel chooseSubjectPnl;
    private javax.swing.JLabel chooseSubjectsLbl;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel confirmPassLbl;
    private javax.swing.JTextField confirmPassTf;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel editProfileLbl;
    private javax.swing.JPanel editProfilePnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lastNameEditLbl;
    private javax.swing.JTextField lastNameEditTf;
    private javax.swing.JLabel linkLbl;
    private javax.swing.JTextField linkTf;
    private javax.swing.JPanel logoutPnl;
    private javax.swing.JLabel nameEditLbl;
    private javax.swing.JTextField nameEditTf;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTf;
    private javax.swing.JLabel oldPassLbl;
    private javax.swing.JTextField oldPassTf;
    private javax.swing.JPanel passwordInfoPnl;
    private javax.swing.JLabel phoneEditLbl;
    private javax.swing.JTextField phoneEditTf;
    private javax.swing.JPanel profilePnl;
    private javax.swing.JLabel projectIdLbl;
    private javax.swing.JTextField projectIdTf;
    private javax.swing.JPanel projectInfoPnl;
    private javax.swing.JButton removeSubjectBtn;
    private javax.swing.JComboBox<String> subjectCb;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JComboBox<String> subjectsCb;
    private javax.swing.JLabel subjectsLbl;
    private javax.swing.JPanel subjectsPnl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JPanel submitProjectPnl;
    private javax.swing.JButton undoBtn;
    private javax.swing.JLabel userNameEditLbl;
    private javax.swing.JTextField userNameEditTf;
    private javax.swing.JPanel viewProjectsPnl;
    // End of variables declaration//GEN-END:variables
}
