/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacherhelper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ViSion
 */
public class TeacherGui extends javax.swing.JFrame {

    /**
     * Creates new form TeacherGui
     */
    private Teacher teacher;
    CareTaker careTaker;
    public TeacherGui(User user) throws SQLException {
        teacher=(Teacher)user;
        careTaker=new CareTaker();
        careTaker.add(teacher.saveStateToMemento());
        
        
        initComponents();
        ResultSet rs=JdbcSingleton.getInstance().getALLSubjectNames();
        while(rs.next()){
            subjectsCb.addItem(rs.getString("name"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        chooseSubjectPnl = new javax.swing.JPanel();
        chooseSubjectsLbl = new javax.swing.JLabel();
        subjectsPnl = new javax.swing.JPanel();
        subjectsLbl = new javax.swing.JLabel();
        subjectsCb = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        addSubjectBtn = new javax.swing.JButton();
        removeSubjectBtn = new javax.swing.JButton();
        addProjectPnl = new javax.swing.JPanel();
        subjectInfoPnl = new javax.swing.JPanel();
        subjectNameLbl = new javax.swing.JLabel();
        subjectNameTf = new javax.swing.JTextField();
        subjectCreditsLbl = new javax.swing.JLabel();
        subjectCreditsCb = new javax.swing.JComboBox<>();
        subjectCreationLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        saveSubjectBtn = new javax.swing.JButton();
        deleteSubjectBtn = new javax.swing.JButton();
        editSubjectBtn = new javax.swing.JButton();
        clearSubjectBtn = new javax.swing.JButton();
        projectCorrectionPnl = new javax.swing.JPanel();
        editProfilePnl = new javax.swing.JPanel();
        profilePnl = new javax.swing.JPanel();
        nameEditLbl = new javax.swing.JLabel();
        nameEditTf = new javax.swing.JTextField();
        lastNameEditLbl = new javax.swing.JLabel();
        lastNameEditTf = new javax.swing.JTextField();
        phoneEditLbl = new javax.swing.JLabel();
        phoneEditTf = new javax.swing.JTextField();
        userNameEditLbl = new javax.swing.JLabel();
        userNameEditTf = new javax.swing.JTextField();
        editProfileLbl = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        changePasswordPnl = new javax.swing.JPanel();
        changePasswordLbl = new javax.swing.JLabel();
        passwordInfoPnl = new javax.swing.JPanel();
        oldPassLbl = new javax.swing.JLabel();
        oldPassTf = new javax.swing.JTextField();
        newPassLbl = new javax.swing.JLabel();
        newPassTf = new javax.swing.JTextField();
        confirmPassLbl = new javax.swing.JLabel();
        confirmPassTf = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        logoutPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher Gui");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        chooseSubjectsLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        chooseSubjectsLbl.setText("CHOOSE SUBJECTS");

        subjectsPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subjectsLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        subjectsLbl.setText("Subjects");

        subjectsCb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout subjectsPnlLayout = new javax.swing.GroupLayout(subjectsPnl);
        subjectsPnl.setLayout(subjectsPnlLayout);
        subjectsPnlLayout.setHorizontalGroup(
            subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectsPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(subjectsLbl)
                .addGap(54, 54, 54)
                .addComponent(subjectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        subjectsPnlLayout.setVerticalGroup(
            subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectsPnlLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(subjectsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectsLbl)
                    .addComponent(subjectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SUBJECT", "CREDITS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTable);

        addSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addSubjectBtn.setText("ADD SUBJECT");

        removeSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        removeSubjectBtn.setText("REMOVE SUBJECT");

        javax.swing.GroupLayout chooseSubjectPnlLayout = new javax.swing.GroupLayout(chooseSubjectPnl);
        chooseSubjectPnl.setLayout(chooseSubjectPnlLayout);
        chooseSubjectPnlLayout.setHorizontalGroup(
            chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(subjectsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(addSubjectBtn)
                        .addGap(53, 53, 53)
                        .addComponent(removeSubjectBtn)))
                .addContainerGap(633, Short.MAX_VALUE))
            .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                    .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(chooseSubjectsLbl))
                        .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                            .addGap(499, 499, 499)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        chooseSubjectPnlLayout.setVerticalGroup(
            chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(subjectsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubjectBtn)
                    .addComponent(removeSubjectBtn))
                .addContainerGap())
            .addGroup(chooseSubjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseSubjectPnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(chooseSubjectsLbl)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Choose Subjects", chooseSubjectPnl);

        subjectInfoPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        subjectInfoPnl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        subjectNameLbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        subjectNameLbl.setText("Name");

        subjectNameTf.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        subjectCreditsLbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        subjectCreditsLbl.setText("Credits");

        subjectCreditsCb.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        subjectCreditsCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6" }));

        javax.swing.GroupLayout subjectInfoPnlLayout = new javax.swing.GroupLayout(subjectInfoPnl);
        subjectInfoPnl.setLayout(subjectInfoPnlLayout);
        subjectInfoPnlLayout.setHorizontalGroup(
            subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectInfoPnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectNameLbl)
                    .addComponent(subjectCreditsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subjectNameTf)
                    .addComponent(subjectCreditsCb, 0, 192, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        subjectInfoPnlLayout.setVerticalGroup(
            subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectInfoPnlLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameLbl)
                    .addComponent(subjectNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(subjectInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectCreditsLbl)
                    .addComponent(subjectCreditsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        subjectCreationLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        subjectCreationLbl.setText("SUBJECT CREATION");

        jTable1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "CREDITS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        saveSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        saveSubjectBtn.setText("SAVE");

        deleteSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        deleteSubjectBtn.setText("DELETE");

        editSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        editSubjectBtn.setText("EDIT");

        clearSubjectBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        clearSubjectBtn.setText("CLEAR");

        javax.swing.GroupLayout addProjectPnlLayout = new javax.swing.GroupLayout(addProjectPnl);
        addProjectPnl.setLayout(addProjectPnlLayout);
        addProjectPnlLayout.setHorizontalGroup(
            addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProjectPnlLayout.createSequentialGroup()
                .addGroup(addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProjectPnlLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(subjectCreationLbl))
                    .addGroup(addProjectPnlLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addProjectPnlLayout.createSequentialGroup()
                                .addComponent(saveSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(subjectInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        addProjectPnlLayout.setVerticalGroup(
            addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProjectPnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(subjectCreationLbl)
                .addGap(18, 18, 18)
                .addGroup(addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(subjectInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(addProjectPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSubjectBtn)
                    .addComponent(deleteSubjectBtn)
                    .addComponent(editSubjectBtn)
                    .addComponent(clearSubjectBtn))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Add Projects", addProjectPnl);

        javax.swing.GroupLayout projectCorrectionPnlLayout = new javax.swing.GroupLayout(projectCorrectionPnl);
        projectCorrectionPnl.setLayout(projectCorrectionPnlLayout);
        projectCorrectionPnlLayout.setHorizontalGroup(
            projectCorrectionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        projectCorrectionPnlLayout.setVerticalGroup(
            projectCorrectionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Project Correction", projectCorrectionPnl);

        profilePnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profilePnl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        nameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameEditLbl.setText("Name");

        nameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        lastNameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lastNameEditLbl.setText("Last Name");

        lastNameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        phoneEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        phoneEditLbl.setText("Phone");

        phoneEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        userNameEditLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        userNameEditLbl.setText("UserName");

        userNameEditTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout profilePnlLayout = new javax.swing.GroupLayout(profilePnl);
        profilePnl.setLayout(profilePnlLayout);
        profilePnlLayout.setHorizontalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameEditLbl)
                    .addComponent(phoneEditLbl))
                .addGap(39, 39, 39)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameEditTf)
                    .addComponent(phoneEditTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(173, 173, 173)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameEditLbl)
                    .addComponent(userNameEditLbl))
                .addGap(45, 45, 45)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameEditTf)
                    .addComponent(userNameEditTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        profilePnlLayout.setVerticalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditLbl)
                    .addComponent(nameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameEditLbl)
                    .addComponent(lastNameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneEditLbl)
                    .addComponent(phoneEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameEditLbl)
                    .addComponent(userNameEditTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        editProfileLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        editProfileLbl.setText("EDIT PROFILE");

        editProfileBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        editProfileBtn.setText("EDIT");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProfilePnlLayout = new javax.swing.GroupLayout(editProfilePnl);
        editProfilePnl.setLayout(editProfilePnlLayout);
        editProfilePnlLayout.setHorizontalGroup(
            editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePnlLayout.createSequentialGroup()
                .addGroup(editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(editProfileLbl))
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProfilePnlLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        editProfilePnlLayout.setVerticalGroup(
            editProfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePnlLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(editProfileLbl)
                .addGap(28, 28, 28)
                .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Edit Profile", editProfilePnl);

        changePasswordLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        changePasswordLbl.setText("CHANGE PASSWORD");

        passwordInfoPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordInfoPnl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        oldPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        oldPassLbl.setText("Old Password");

        oldPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        newPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        newPassLbl.setText("New Password");

        newPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        confirmPassLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        confirmPassLbl.setText("Confirm Password");

        confirmPassTf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout passwordInfoPnlLayout = new javax.swing.GroupLayout(passwordInfoPnl);
        passwordInfoPnl.setLayout(passwordInfoPnlLayout);
        passwordInfoPnlLayout.setHorizontalGroup(
            passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPassLbl)
                            .addComponent(newPassLbl)))
                    .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(confirmPassLbl)))
                .addGap(116, 116, 116)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldPassTf)
                    .addComponent(newPassTf)
                    .addComponent(confirmPassTf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        passwordInfoPnlLayout.setVerticalGroup(
            passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInfoPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLbl)
                    .addComponent(oldPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassLbl)
                    .addComponent(newPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(passwordInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassLbl)
                    .addComponent(confirmPassTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        confirmBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        confirmBtn.setText("CONFIRM");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        undoBtn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        undoBtn.setText("UNDO");
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePasswordPnlLayout = new javax.swing.GroupLayout(changePasswordPnl);
        changePasswordPnl.setLayout(changePasswordPnlLayout);
        changePasswordPnlLayout.setHorizontalGroup(
            changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPnlLayout.createSequentialGroup()
                .addGroup(changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(changePasswordLbl))
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(passwordInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changePasswordPnlLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        changePasswordPnlLayout.setVerticalGroup(
            changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(changePasswordLbl)
                .addGap(30, 30, 30)
                .addComponent(passwordInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(changePasswordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Change Password", changePasswordPnl);

        javax.swing.GroupLayout logoutPnlLayout = new javax.swing.GroupLayout(logoutPnl);
        logoutPnl.setLayout(logoutPnlLayout);
        logoutPnlLayout.setHorizontalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        logoutPnlLayout.setVerticalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Logout", logoutPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
        if(jTabbedPane1.getSelectedIndex()==3){
          try {
              
              ResultSet rs=JdbcSingleton.getInstance().loadProfile(teacher);
              while(rs.next()){
                  nameEditTf.setText(rs.getString("name"));
                  lastNameEditTf.setText(rs.getString("lastname"));
                  phoneEditTf.setText(rs.getString("phone"));
                  userNameEditTf.setText(rs.getString("username"));
              }
          } catch (SQLException ex) {
              Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      
        if(jTabbedPane1.getSelectedIndex()==5){
          teacher.logout(this);
      }
      
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
               try {
            teacher.editProfile(teacher, nameEditTf.getText(), lastNameEditTf.getText(), phoneEditTf.getText(), userNameEditTf.getText(), this);
            teacher.setName(nameEditTf.getText());
            teacher.setLastName(lastNameEditTf.getText());
            teacher.setPhone(phoneEditTf.getText());
            teacher.setUsername(userNameEditTf.getText());
        } catch (SQLException ex) {
            Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if(oldPassTf.getText()==""||newPassTf.getText()==""||confirmPassTf.getText()==""){
            JOptionPane.showMessageDialog(this, "Some Fields Are Missing !!");
        }
        else{
            try {
                if(!JdbcSingleton.getInstance().verifyOldPassword(teacher, oldPassTf.getText())){
                    JOptionPane.showMessageDialog(this, "Wrong Old Password !!");
                }
                else{
                    
                    if(!newPassTf.getText().equals(confirmPassTf.getText())){
                        JOptionPane.showMessageDialog(this, "New Pass And Confirmation Are Not The Same !!");
                    }
                    else{
                        teacher.changePassword(teacher, newPassTf.getText(), this);
                        teacher.setPassword(newPassTf.getText());
                        careTaker.add(teacher.saveStateToMemento());
                        
                        
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
         if(careTaker.getList().size()>1){
            try {
                teacher.changePassword(teacher,careTaker.get(careTaker.getList().size()-2).getState(), this);
            } catch (SQLException ex) {
                Logger.getLogger(AdminGui.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            teacher.setPassword(careTaker.get(careTaker.getList().size()-2).getState());
            
            careTaker.getList().remove(careTaker.getList().size()-1);
        }
        else{
            JOptionPane.showMessageDialog(this, "There Is Nothing To Undo !!");
        }
    }//GEN-LAST:event_undoBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addProjectPnl;
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JLabel changePasswordLbl;
    private javax.swing.JPanel changePasswordPnl;
    private javax.swing.JPanel chooseSubjectPnl;
    private javax.swing.JLabel chooseSubjectsLbl;
    private javax.swing.JButton clearSubjectBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel confirmPassLbl;
    private javax.swing.JTextField confirmPassTf;
    private javax.swing.JButton deleteSubjectBtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel editProfileLbl;
    private javax.swing.JPanel editProfilePnl;
    private javax.swing.JButton editSubjectBtn;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastNameEditLbl;
    private javax.swing.JTextField lastNameEditTf;
    private javax.swing.JPanel logoutPnl;
    private javax.swing.JLabel nameEditLbl;
    private javax.swing.JTextField nameEditTf;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTf;
    private javax.swing.JLabel oldPassLbl;
    private javax.swing.JTextField oldPassTf;
    private javax.swing.JPanel passwordInfoPnl;
    private javax.swing.JLabel phoneEditLbl;
    private javax.swing.JTextField phoneEditTf;
    private javax.swing.JPanel profilePnl;
    private javax.swing.JPanel projectCorrectionPnl;
    private javax.swing.JButton removeSubjectBtn;
    private javax.swing.JButton saveSubjectBtn;
    private javax.swing.JLabel subjectCreationLbl;
    private javax.swing.JComboBox<String> subjectCreditsCb;
    private javax.swing.JLabel subjectCreditsLbl;
    private javax.swing.JPanel subjectInfoPnl;
    private javax.swing.JLabel subjectNameLbl;
    private javax.swing.JTextField subjectNameTf;
    private javax.swing.JComboBox<String> subjectsCb;
    private javax.swing.JLabel subjectsLbl;
    private javax.swing.JPanel subjectsPnl;
    private javax.swing.JButton undoBtn;
    private javax.swing.JLabel userNameEditLbl;
    private javax.swing.JTextField userNameEditTf;
    // End of variables declaration//GEN-END:variables
}
